### ISSUE TITLE
subscribeWithNotifications onMessage callback never executed

### ISSUE THREAD

**Issue by Dliix66** [realtime-framework/RealtimeMessaging-iOS-Swift#8]
Hello,

when calling:

```
ortc.subscribeWithNotifications("user_channel", subscribeOnReconnected: true, onMessage: {
            (ortcClient:OrtcClient!, channel:String!, msg:String!) -> Void in
            UIApplication.shared.applicationIconBadgeNumber += 1
        })
```

The callback `onMessage` is never executed no matter if the application is running or not. Thus I can't increment my badge count.

Thanks,

PS: I still receive the notifications when the app is not running.

***SOLUTION***:

Using the new pod (`RealtimeMessaging-iOS-Swift3-Push`) instead of `RealtimeMessaging-iOS-Swift3` solved it for me.

**Comment by realtime-framework** [comment]
When the app is running is the ortc client connected when you send the message? If not the onMessage callback will not be invoked.

**Comment by Dliix66** [comment]
Hello,

Yes it is connected, that is why I do not understand this behavior.

Thanks for looking into it.

**Comment by realtime-framework** [comment]
Can you send us a small project replicating the issue? Please send it to framework(at)realtime.co

**Comment by Dliix66** [comment]
I've just sent it. I've put some prints so you can see what's going on from the console. I can not receive more than one notification per launch, but I can receive unlimited notifications when the app is either in the background or killed.

Re-reading the ios push tutorial ([iOS Push Notifications](http://messaging-public.realtime.co/documentation/starting-guide/mobilePushAPNS.html)), I noticed that the delegate `RealtimePushAppDelegate` does not exist and thus I cannot call `super.application(application:didFinishLaunchingWithOptions:)`. 
Do you think that might be the problem ? Is yes, has it be renamed ? I cannot find such delegate.

Link to `RealTimePushAppDelegate`: [http://messaging-public.realtime.co/documentation/ios/2.1.0/Classes/RealtimePushAppDelegate.html](http://messaging-public.realtime.co/documentation/ios/2.1.0/Classes/RealtimePushAppDelegate.html)

**Comment by realtime-framework** [comment]
The RealtimePushAppDelegate is only valid for ObjC. In Swift we are using a category implemented through the RealtimeMessaging-iOS-Swift3-Push Pod

**Comment by Dliix66** [comment]
Alright, That's what I thought, but I wasn't sure. Thanks !
