### ISSUE TITLE
Exception "URL and Cluster URL are null or empty"

### ISSUE THREAD

**Issue by mcastro-dev** [realtime-framework/RealtimeMessaging-iOS-Swift#9]
I'm getting this exception after user disconnects from Realtime (due to manual logout) and reconnects back in (via manual login).
The exception is thrown in the connect(_:) method of the OrtcClient class:

`} else if self.url != nil && self.clusterUrl != nil {`
`    self.delegateExceptionCallback(self, error: self.generateError("URL and Cluster URL are null or empty"))`
`}`

It should check == nil, right?

The problem is that I set the clusterUrl before connecting, but I never assigned the url. But when I disconnect, the lib sets the url, making them both != nil.

**Comment by realtime-framework** [comment]
Hi @Kastr, thanks for the heads-up. A new Pod version with a fix was pushed. Please try it and let us know.

**Comment by mcastro-dev** [comment]
@realtime-framework thank you for the quick response.
I will be able to try it soon. Thanks.

**Comment by mcastro-dev** [comment]
@realtime-framework  Yes, the new version fixed it. Thank you!
